<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL6gPwlP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL6gPwlP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL6gPwlP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL6gPwlP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL6gPwlP\App_KernelDevDebugContainer([
    'container.build_hash' => 'L6gPwlP',
    'container.build_id' => '83aeb7c9',
    'container.build_time' => 1627244101,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL6gPwlP');
