<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Xhn2Fb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Xhn2Fb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4Xhn2Fb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4Xhn2Fb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4Xhn2Fb\App_KernelDevDebugContainer([
    'container.build_hash' => '4Xhn2Fb',
    'container.build_id' => '24aa9bd8',
    'container.build_time' => 1627284123,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Xhn2Fb');
